spring:
    application:
        name: resource-server
    datasource:
      url: jdbc:h2:mem:test_db
      username: db
      password:

    h2:
      console:
        enabled: true

    security:
      oauth2:
        resource-server:
          jwt:
            issuer-uri: http://localhost:8080/realms/master

server:
    port: 8000